import type { IntelData } from './types';

export class IntelFormatter {
  /**
   * Format date nicely
   */
  private formatDate(dateStr: string): string {
    const date = new Date(dateStr);
    const options: Intl.DateTimeFormatOptions = {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    };
    return date.toLocaleDateString('en-US', options);
  }

  /**
   * Generate Markdown report from collected data
   */
  generateMarkdown(data: IntelData): string {
    const { reddit, hn, github, date } = data;

    const totalRedditPosts = Object.values(reddit).reduce((sum, posts) => sum + posts.length, 0);

    let md = `# Intel Report — ${date}

**Collection Date:** ${this.formatDate(date)}
**Timezone:** America/Buenos_Aires
**Collection Method:** Direct API fetch (Reddit JSON, HN Firebase, GitHub API)
**Sources:** ${totalRedditPosts} Reddit posts, ${hn.length} HN stories, ${github.length} GitHub releases

---

`;

    // Technology Section
    md += `## 🚀 Technology

`;

    const techSubs = ['LocalLLaMA', 'ClaudeAI'];
    for (const sub of techSubs) {
      const posts = reddit[sub] || [];
      if (posts.length === 0) continue;

      md += `### r/${sub}

`;
      for (const post of posts.slice(0, 5)) {
        md += `#### [${post.title}](${post.url})
- **Score:** ${post.score} upvotes / ${post.comments} comments
- **Summary:** ${post.summary}

`;
      }
    }

    // Hacker News Section
    if (hn.length > 0) {
      md += `## 🟠 Hacker News

`;
      for (const story of hn.slice(0, 8)) {
        md += `#### [${story.title}](${story.url})
- **Points:** ${story.score} | **Comments:** ${story.comments}

`;
      }
    }

    // GitHub Releases Section
    if (github.length > 0) {
      md += `## 🔧 GitHub Releases (Last 7 Days)

| Repository | Version | Published | Key Changes |
|------------|---------|-----------|-------------|
`;

      for (const rel of github) {
        const isNew = rel.isRecent ? ' 🆕' : '';
        const shortDate = rel.published.split('T')[0];
        const shortBody = rel.body.substring(0, 80).replace(/\|/g, ',') + '...';
        md += `| ${rel.repo} | [${rel.version}${isNew}](${rel.url}) | ${shortDate} | ${shortBody} |
`;
      }

      md += `
`;
    }

    // Summary Section
    md += `## 📊 Collection Summary

| Source | Posts | Top Score |
|--------|-------|-----------|
`;

    for (const [subName, posts] of Object.entries(reddit)) {
      const maxScore = posts.length > 0 ? Math.max(...posts.map((p) => p.score)) : 0;
      md += `| r/${subName} | ${posts.length} | ${maxScore > 0 ? '🔥 ' + maxScore : '-'} |
`;
    }

    md += `| Hacker News | ${hn.length} | ${hn.length > 0 ? '🔥 ' + Math.max(...hn.map((h) => h.score)) : '-'} |
`;
    md += `| GitHub Releases | ${github.length} | - |
`;

    // Footer
    md += `
---

*Generated by intel-gatherer v3.0.0 (TypeScript/Bun)*
*Collection timestamp: ${new Date().toISOString()}*
`;

    return md;
  }

  /**
   * Generate simple HTML report
   */
  generateHTML(markdown: string, date: string): string {
    // Simple markdown to HTML conversion
    let html = markdown
      .replace(/^# (.+)$/gm, '<h1>$1</h1>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/^---$/gm, '<hr>');

    const template = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Intel Report — ${date}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-50 text-slate-900">
  <div class="container mx-auto px-4 py-8 max-w-6xl">
    <div class="bg-white rounded-lg shadow-lg p-8">
      ${html}
    </div>
  </div>
</body>
</html>`;

    return template;
  }
}
