# Intel Collection Sources Configuration v4.0
# Category-based unified format

settings:
  github_token: "${GITHUB_TOKEN}"
  reddit_delay_ms: 800
  hn_story_limit: 15
  hn_concurrency: 5

categories:
  - id: ai_models
    name: "AI Models & Local LLMs"
    emoji: "\U0001F680"
    sources:
      - type: reddit
        name: LocalLLaMA
        url: "https://www.reddit.com/r/LocalLLaMA/hot.json?limit=10"
        min_score: 50
        min_comments: 20

      - type: reddit
        name: ClaudeAI
        url: "https://www.reddit.com/r/ClaudeAI/hot.json?limit=10"
        min_score: 50
        min_comments: 20

  - id: crypto
    name: "Crypto & Blockchain"
    emoji: "\U0001FA99"
    sources:
      - type: reddit
        name: Bitcoin
        url: "https://www.reddit.com/r/Bitcoin/hot.json?limit=10"
        min_score: 50
        min_comments: 20

      - type: reddit
        name: ethereum
        url: "https://www.reddit.com/r/ethereum/hot.json?limit=10"
        min_score: 50
        min_comments: 20

  - id: finance
    name: "Finance & Trading"
    emoji: "\U0001F4C8"
    sources:
      - type: reddit
        name: algotrading
        url: "https://www.reddit.com/r/algotrading/hot.json?limit=10"
        min_score: 50
        min_comments: 20

  - id: self_hosted
    name: "Self-Hosted & Homelab"
    emoji: "\U0001F3E0"
    sources:
      - type: reddit
        name: selfhosted
        url: "https://www.reddit.com/r/selfhosted/hot.json?limit=10"
        min_score: 30
        min_comments: 10

      - type: reddit
        name: homelab
        url: "https://www.reddit.com/r/homelab/hot.json?limit=10"
        min_score: 40
        min_comments: 10

  - id: entertainment
    name: "Movies & Series"
    emoji: "\U0001F3AC"
    sources:
      - type: reddit
        name: movies
        url: "https://www.reddit.com/r/movies/hot.json?limit=10"
        min_score: 50
        min_comments: 20

      - type: reddit
        name: television
        url: "https://www.reddit.com/r/television/hot.json?limit=10"
        min_score: 30
        min_comments: 15

  - id: hackernews
    name: "Hacker News"
    emoji: "\U0001F7E0"
    sources:
      - type: hn
        name: frontpage
        url: "https://hacker-news.firebaseio.com/v0/topstories.json"

  - id: releases
    name: "GitHub Releases"
    emoji: "\U0001F527"
    sources:
      - type: github
        repo: langchain-ai/langchain

      - type: github
        repo: langchain-ai/langgraph

      - type: github
        repo: fastapi/fastapi

      - type: github
        repo: pydantic/pydantic

      - type: github
        repo: vercel/next.js

      - type: github
        repo: dotnet/aspnetcore

analysis:
  keywords:
    technology:
      - openclaw
      - langchain
      - langgraph
      - n8n
      - dify
      - autogpt
      - agent
      - local llm
      - swarm
      - multi-agent
      - workflow
    tools:
      - claude
      - gpt-4
      - gpt-5
      - ollama
      - llama
      - mistral
      - fastapi
      - nextjs
      - react
      - docker
    crypto:
      - bitcoin
      - ethereum
      - solana
      - crypto
      - blockchain
      - trading
      - defi
  llm_summary:
    enabled: true
    temperature: 0.4
